### ISSUE TITLE
Too little data for declared Content-Length

### ISSUE THREAD

**Issue by Yimura** [ysfchn/SamFetch#8]
Path: `/EUX/SM-F926B`

**Server Environment:**
- Docker
- python:3.7.12-buster

**Client Environment:**
- Chrome (95.0.4638.69)
- curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

<details>
  <summary>Call Stack:</summary>
  
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/responses.py", line 227, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "/usr/local/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 604, in _run_wrapped_task
    await coro
  File "/usr/local/lib/python3.7/site-packages/starlette/responses.py", line 223, in wrap
    await func()
  File "/usr/local/lib/python3.7/site-packages/starlette/responses.py", line 217, in stream_response
    await send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 477, in send
    output = self.conn.send(event)
  File "/usr/local/lib/python3.7/site-packages/h11/_connection.py", line 468, in send
    data_list = self.send_with_data_passthrough(event)
  File "/usr/local/lib/python3.7/site-packages/h11/_connection.py", line 501, in send_with_data_passthrough
    writer(event, data_list.append)
  File "/usr/local/lib/python3.7/site-packages/h11/_writers.py", line 60, in __call__
    self.send_eom(event.headers, write)
  File "/usr/local/lib/python3.7/site-packages/h11/_writers.py", line 83, in send_eom
    raise LocalProtocolError("Too little data for declared Content-Length")
h11._util.LocalProtocolError: Too little data for declared Content-Length
INFO:     192.168.96.1:32934 - "GET /EUX/SM-F926B HTTP/1.1" 200 OK
```
</details>

**Comment by ysfchn** [comment]
Sorry for the inconvenience. Yes, I'm aware of the issue and working on a fix for a while. The reason is SamFetch sends the full firmware size to download client (so your download client can display a progress bar and ETA), however decrypting firmware causes the firmware size different from actual size. 

I made changes in ["refactor" branch](https://github.com/ysfchn/SamFetch/tree/refactor) a while ago and disabled presenting firmware size to download client when decryption has enabled yesterday. The "refactor" branch should work as it is almost finished. You can deploy from that branch and try downloading firmware again. (Note: The direct downloading path has changed from `/<REGION>/<MODEL>` to `/direct/<REGION>/<MODEL>` in "refactor" branch.) 

Hope this helps!

**Comment by Yimura** [comment]
No problem I wasn't aware this issue was fixed in the refactor branch, this way we can track when the master branch is updated.

**Comment by ysfchn** [comment]
This now should be fixed! Let me know if you encounter any errors.
